apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pingpong
  namespace: argocd  
spec:
  project: default
  source:
    repoURL: https://github.com/melisabunjaku/pingpong-gitops
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: project-exercises  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
