apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong-deployment
  namespace: project-exercises
  labels:
    app: pingpong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      containers:
        - name: pingpong
          image: mb2821/pingpong:latest
          ports:
            - containerPort: 3001
          env:
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: pingpong-config
                  key: POSTGRES_HOST
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
          volumeMounts:
            - name: shared-data
              mountPath: /usr/src/app/shared
          readinessProbe:
            httpGet:
              path: /pingpong
              port: 3001
            initialDelaySeconds: 20  
            periodSeconds: 10
            failureThreshold: 3
      volumes:
        - name: shared-data
          persistentVolumeClaim:
            claimName: shared-pvc
